# Requires docker-compose >= 1.29.0
version: '3.8'

services:
  # TODO: update CKB version
  ckb:
    image: nervos/ckb:v0.113.1
    user: root
    ports:
      - 8114:8114   # rpc
      - 8115:8115   # p2p network
    volumes:
      - ./ckb:/var/lib/ckb
    command: [ "run", "-C", "/var/lib/ckb" ]

  # TODO: update CKB version
  ckb-miner:
    init: true
    image: nervos/ckb:v0.113.1
    user: root
    volumes:
      - ./ckb:/var/lib/ckb
    command: [ "miner", "-C", "/var/lib/ckb" ]

  # "nervos/ckb" image have no http clients to do health check for CKB.
  # This short-term service act as a workaround to do health check.
  check-ckb-started-successfully:
    image: curlimages/curl
    volumes:
      - ./ckb:/var/lib/ckb
    command: [ 'http://ckb:8114', '-H', 'content-type: application/json', '-d', '{ "id": 2, "jsonrpc": "2.0", "method": "get_tip_block_number", "params": [] }' ]
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 1000
    depends_on:
      - ckb
